export const DashboardRoutes =[
    { path: "/admin-dashboard/configurations", label: "Configuration settings" },
    { path: "/admin-dashboard/configurations/product-settings", label: "Savings Product Settings" },
    { path: "/admin-dashboard/configurations/product-settings/loan", label: "Loan Product settings" },
    { path: "/admin-dashboard/configurations/product-settings/investments", label: "Investment Product settings" },
    { path: "/admin-dashboard/configurations/manage-bank-account", label: "Bank Account Management" },
    { path: "/admin-dashboard/configurations/change-password", label: "Change Password" },
    { path: "/admin-dashboard/configurations/manage-assets", label: "Asset Category" },
    { path: "/admin-dashboard/configurations/manage-asset-class", label: "Asset Class" },
    { path: "/admin-dashboard/configurations/manage-asset-disposal", label: "Asset Disposal" },
    { path: "/admin-dashboard/admin-tasks", label: "Manage GL Account"},
    { path: "/admin-dashboard/admin-tasks/manage-users", label: "Manage Users"},
    { path: "/admin-dashboard/admin-tasks/manage-roles", label: "Manage Roles"},
    { path: "/admin-dashboard/admin-tasks/outstanding-subscription", label: "Outstanding Subscription"},
    { path: "/admin-dashboard/admin-tasks/map-statutory", label: "Map Statutory Report"},
    { path: "/admin-dashboard/admin-tasks/financial-year-closure", label: "Financial Year Closure"},
    { path: "/admin-dashboard/communications", label: "Communication Broadcast"},
    { path: "/admin-dashboard/member-management/members", label: "Member Management"},
    { path: "/admin-dashboard/member-management/member-deduction", label: "Member Deduction"},
    { path: "/admin-dashboard/member-management/member-account", label: "Member Account Creation"},
    { path: "/admin-dashboard/member-management/member-account/close-account", label: "Close Member Account"},
    { path: "/admin-dashboard/member-management/member-account/account-reactivation", label: "Reactivate Member Account"},
    { path: "/admin-dashboard/accounting", label: "Accounting Bulk Upload"},
    { path: "/admin-dashboard/accounting/deposit", label: "Accounting Deposit"},
    { path: "/admin-dashboard/accounting/transfer", label: "Accounting Transfer"},
    { path: "/admin-dashboard/accounting/withdrawal", label: "Accounting Withdrawal"},
    { path: "/admin-dashboard/accounting/deduction-upload", label: "Accounting Deduction Upload"},
    { path: "/admin-dashboard/elections", label: "Elections"},
    { path: "/admin-dashboard/elections/position-eligibility", label: "Position Set up"},
    { path: "/admin-dashboard/elections/approval", label: "Election Application Approval"},
    { path: "/admin-dashboard/elections/candidates", label: "Election Candidate"},
    { path: "/admin-dashboard/elections/election-reports", label: "Election Report"},
    { path: "/admin-dashboard/inventory-management", label: "Inventory Item Category"},
    { path: "/admin-dashboard/inventory-management/vendor", label: "Vendor Management"},
    { path: "/admin-dashboard/inventory-management/register-items", label: "Inventory Item Registration"},
    { path: "/admin-dashboard/loan-management", label: "Loan Application Management"},
    { path: "/admin-dashboard/loan-management/view-loan-application", label: "View Loan Application"},
    { path: "/admin-dashboard/loan-management/bulk-loan", label: "Bulk Loan Application"},
    { path: "/admin-dashboard/loan-management/disbursement", label: "Loan Disbursement"},
    { path: "/admin-dashboard/loan-management/status", label: "Loan Status"},
    { path: "/admin-dashboard/loan-management/loan-desave", label: "Loan Desave"},
    { path: "/admin-dashboard/loan-management/partial-desave", label: "Loan Partial Desave"},
    { path: "/admin-dashboard/loan-management/repayment", label: "Loan Repayment"},
    { path: "/admin-dashboard/loan-management/skipping", label: "Loan Skipping"},
    { path: "/admin-dashboard/loan-management/restructure", label: "Loan Restructure"},
    { path: "/admin-dashboard/investments", label: "Investments"},
    { path: "/admin-dashboard/investment-status", label: "Investment Status"},
    { path: "/admin-dashboard/investments/partial-pay", label: "Investment Partial Pay"},
    { path: "/admin-dashboard/investments/liquidate-investment", label: "Liquidate Investment"},
    { path: "/admin-dashboard/investments/investment-report", label: "Investment Report"},
    { path: "/admin-dashboard/shares-management", label: "Shares Configuration"},
    { path: "/admin-dashboard/shares-management/shares-register", label: "Buy/Withdraw Shares"},
    { path: "/admin-dashboard/shares-management/shares-report", label: "Shares Report"},
    { path: "/admin-dashboard/support", label: "Contact Us"},
    { path: "/admin-dashboard/support/faqs", label: "Faqs"},
    { path: "/admin-dashboard/support/email-support", label: "Email Support"},

]