export const data=[
    {"id":1,"product_code":"49349-583","product_name":"Aufderhar, Cruickshank and Bayer","product_class":"Asphalt Paving","actions":"Female"},
{"id":2,"product_code":"10812-332","product_name":"Breitenberg-Dibbert","product_class":"Asphalt Paving","actions":"Female"},
{"id":3,"product_code":"64117-985","product_name":"Kiehn-Moen","product_class":"Plumbing & Medical Gas","actions":"Female"},
{"id":4,"product_code":"68382-024","product_name":"Waelchi Group","product_class":"Construction Clean and Final Clean","actions":"Male"},
{"id":5,"product_code":"0006-0106","product_name":"Cassin, Boyer and Brown","product_class":"Masonry","actions":"Female"},
{"id":6,"product_code":"49999-774","product_name":"Kertzmann, Howe and Cummings","product_class":"Electrical","actions":"Male"},
{"id":7,"product_code":"13668-033","product_name":"Dooley-Jaskolski","product_class":"Structural and Misc Steel (Fabrication)","actions":"Female"},
{"id":8,"product_code":"24470-906","product_name":"Macejkovic Inc","product_class":"EIFS","actions":"Female"},
{"id":9,"product_code":"0268-0826","product_name":"Larkin, Ruecker and Nikolaus","product_class":"Marlite Panels (FED)","actions":"Female"},
{"id":10,"product_code":"21695-394","product_name":"Runte, Kub and Fritsch","product_class":"Masonry","actions":"Female"},
{"id":11,"product_code":"12546-720","product_name":"McClure and Sons","product_class":"Drilled Shafts","actions":"Male"},
{"id":12,"product_code":"33261-045","product_name":"Wilderman, Roberts and Monahan","product_class":"Retaining Wall and Brick Pavers","actions":"Female"},
{"id":13,"product_code":"63187-066","product_name":"Stokes Group","product_class":"Prefabricated Aluminum Metal Canopies","actions":"Male"},
{"id":14,"product_code":"44009-801","product_name":"Welch, Baumbach and Stehr","product_class":"Structural & Misc Steel Erection","actions":"Male"},
{"id":15,"product_code":"68428-109","product_name":"Schmeler Group","product_class":"Retaining Wall and Brick Pavers","actions":"Male"},
{"id":16,"product_code":"48951-3003","product_name":"Reynolds Group","product_class":"Casework","actions":"Male"},
{"id":17,"product_code":"63629-1396","product_name":"Ebert, Johns and Nikolaus","product_class":"Structural & Misc Steel Erection","actions":"Male"},
{"id":18,"product_code":"43406-0028","product_name":"Ryan LLC","product_class":"Drywall & Acoustical (MOB)","actions":"Male"},
{"id":19,"product_code":"68745-2008","product_name":"Heller, Osinski and Lehner","product_class":"Masonry & Precast","actions":"Male"},
{"id":20,"product_code":"53675-152","product_name":"Bartoletti, Murazik and Macejkovic","product_class":"Overhead Doors","actions":"Female"},
{"id":21,"product_code":"0007-3230","product_name":"Reilly, Langosh and Schmidt","product_class":"Drywall & Acoustical (MOB)","actions":"Male"},
{"id":22,"product_code":"0486-1125","product_name":"Braun-Lindgren","product_class":"Casework","actions":"Female"},
{"id":23,"product_code":"42254-166","product_name":"Heathcote LLC","product_class":"Hard Tile & Stone","actions":"Male"},
{"id":24,"product_code":"0135-0503","product_name":"Harber-Champlin","product_class":"Rebar & Wire Mesh Install","actions":"Female"},
{"id":25,"product_code":"66715-6831","product_name":"Rath-Bradtke","product_class":"Overhead Doors","actions":"Female"},
{"id":26,"product_code":"64778-0213","product_name":"Dickinson and Sons","product_class":"Framing (Wood)","actions":"Male"},
{"id":27,"product_code":"68428-103","product_name":"Hauck Inc","product_class":"Framing (Steel)","actions":"Female"},
{"id":28,"product_code":"0264-9350","product_name":"Kessler, Swaniawski and Stroman","product_class":"Roofing (Metal)","actions":"Non-binary"},
{"id":29,"product_code":"50436-7286","product_name":"Baumbach-Auer","product_class":"Site Furnishings","actions":"Male"},
{"id":30,"product_code":"60432-833","product_name":"Hansen, Abbott and O'Connell","product_class":"Termite Control","actions":"Female"},
{"id":31,"product_code":"53113-657","product_name":"Wunsch, Lockman and West","product_class":"Retaining Wall and Brick Pavers","actions":"Female"},
{"id":32,"product_code":"55319-393","product_name":"Johnston Inc","product_class":"Ornamental Railings","actions":"Male"},
{"id":33,"product_code":"42291-850","product_name":"Harber, Ferry and Gusikowski","product_class":"Elevator","actions":"Male"},
{"id":34,"product_code":"30142-182","product_name":"Gleason LLC","product_class":"Sitework & Site Utilities","actions":"Male"},
{"id":35,"product_code":"17089-383","product_name":"Huels-Schaefer","product_class":"Masonry & Precast","actions":"Female"},
{"id":36,"product_code":"51143-124","product_name":"Wyman and Sons","product_class":"Roofing (Metal)","actions":"Male"},
{"id":37,"product_code":"42291-755","product_name":"Heaney Group","product_class":"Rebar & Wire Mesh Install","actions":"Male"},
{"id":38,"product_code":"55154-2434","product_name":"Wyman-Berge","product_class":"Framing (Wood)","actions":"Non-binary"},
{"id":39,"product_code":"67457-438","product_name":"Cole Group","product_class":"Sitework & Site Utilities","actions":"Female"},
{"id":40,"product_code":"50474-710","product_name":"Wunsch, Koelpin and Murphy","product_class":"Asphalt Paving","actions":"Male"},
{"id":41,"product_code":"54868-2207","product_name":"Sauer, Mueller and Glover","product_class":"Construction Clean and Final Clean","actions":"Female"},
{"id":42,"product_code":"55910-668","product_name":"McCullough and Sons","product_class":"Elevator","actions":"Female"},
{"id":43,"product_code":"51824-164","product_name":"Runte Group","product_class":"Prefabricated Aluminum Metal Canopies","actions":"Female"},
{"id":44,"product_code":"42507-554","product_name":"Hermiston-Wehner","product_class":"Doors, Frames & Hardware","actions":"Female"},
{"id":45,"product_code":"21695-485","product_name":"Wolff LLC","product_class":"Casework","actions":"Female"},
{"id":46,"product_code":"54458-980","product_name":"Schuppe Inc","product_class":"Hard Tile & Stone","actions":"Female"},
{"id":47,"product_code":"0591-0345","product_name":"Kihn, Howe and Beer","product_class":"Roofing (Metal)","actions":"Male"},
{"id":48,"product_code":"0641-6027","product_name":"King, Crooks and Purdy","product_class":"Masonry & Precast","actions":"Female"},
{"id":49,"product_code":"14783-313","product_name":"Block, Bergstrom and Turner","product_class":"Temp Fencing, Decorative Fencing and Gates","actions":"Female"},
{"id":50,"product_code":"64942-1356","product_name":"Simonis, Johns and Emard","product_class":"Fire Protection","actions":"Female"}

]